### PR TITLE
fix: fix table control on firefox

### PR DESCRIPTION
**Pull request by tomquinonero**
Fix hyphens issue on table controls on firefox.

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
@tomquinonero I’d suggest fixing this on yoco’s classes instead by using an `!important`, since this will **never** be good behavior in yoco.

**Comment by ostoc** [comment]
@tomquinonero i found there is no issue on Safari and Firefox. Which version of Firefox you are using?

**Comment by FlorianWendelborn** [comment]
@ostoc For an unknown reason, this bug is only triggered in AMPI. We don’t have any custom css that should interfere here though.

The bug appears in my Firefox Developer Edition.

image

**Comment by FlorianWendelborn** [comment]
@ostoc It would be great if this fix could be moved to the `.yoco` class, as I suggested, or is there ever a reason why it should add hyphens in a ligature?

**Pull request merged**
