### PR TITLE
Update composition api to latest possible

### PR DESCRIPTION
**Pull request by carsoli**
We want to migrate all our packages to use vue3
As a first step, we upgraded to latest vue-composition-api for vue-next compatability purposes

### CODE REVIEW

**Comment by carsoli** [comment]
@santiagoballadares we verified that Kotti works - I ask of you to basically thoroughly test this at your earliest convenience so I can merge/publish ad have the user-app PR ready for merge

**Review by santiagoballadares — DISMISSED** [review]
FT done, LGTM

**Comment by RueRivoli** [comment]
Ft ok, 
@carsoli why does the flush: 'post' is now necessary ?

**Comment by carsoli** [comment]
> Ft ok, @carsoli why does the flush: 'post' is now necessary on these watchers ?

yes will cover this today in the chapter meet

**Review by santiagoballadares — APPROVED** [review]

**Pull request merged**
